FROM sbtscala/scala-sbt:eclipse-temurin-18.0.2.1_1_1.8.1_3.2.1 as builder

WORKDIR /app

COPY build.sbt .
COPY project project
COPY images images
COPY repository repository

RUN sbt clean
RUN sbt assembly

FROM openjdk:8-jre-alpine

WORKDIR /app

COPY --from=builder /app/images/target/scala-2.13/*.jar /app/images-app.jar
COPY --from=builder /app/images/src/main/resources/application.conf /app/images/src/main/resources/application.conf
COPY --from=builder /app/repository/src/main/resources/ /app/repository/src/main/resources/

EXPOSE 8083

ENTRYPOINT java -cp /app/*.jar images.ImagesMain
