FROM sbtscala/scala-sbt:eclipse-temurin-18.0.2.1_1_1.8.1_3.2.1 as builder

WORKDIR /app

COPY . .

RUN sbt clean
RUN sbt assembly

FROM openjdk:8-jre-alpine

WORKDIR /app

COPY --from=builder /app/auth/target/scala-2.13/*.jar /app/auth-app.jar
COPY --from=builder /app/auth/src/main/resources/application.conf /app/auth-application.conf

EXPOSE 8080

ENV APP_CONFIG /app/auth-application.conf

ENTRYPOINT java -Dconfig.file=$APP_CONFIG -cp /app/auth-app.jar auth.AuthMain
