FROM sbtscala/scala-sbt:eclipse-temurin-18.0.2.1_1_1.8.1_3.2.1 as builder

WORKDIR /app

COPY . .

RUN sbt clean
RUN sbt assembly

FROM openjdk:8-jre-alpine

WORKDIR /app

COPY --from=builder /app/routing/target/scala-2.13/*.jar /app/routing-app.jar
COPY --from=builder /app/routing/src/main/resources/application.conf /app/routing-application.conf

EXPOSE 8081

ENV APP_CONFIG /app/routing-application.conf

ENTRYPOINT java -Dconfig.file=$APP_CONFIG -cp /app/routing-app.jar routing.RoutingMain
