FROM hseeberger/scala-sbt:8u222_1.3.5_2.13.1 as builder

WORKDIR /app

COPY . .

RUN sbt "project auth" compile package

FROM openjdk:8-jre-alpine

WORKDIR /app

COPY --from=builder /app/auth/target/scala-2.13/auth-app_2.13-1.0.jar /app/auth-app.jar
COPY --from=builder /app/auth/src/main/resources/application.conf /app/auth-application.conf

EXPOSE 8080

ENV APP_ENV production
ENV APP_CONFIG /app/auth-application.conf

ENTRYPOINT java -Dconfig.file=$APP_CONFIG -cp /app/auth-app.jar auth.AuthMain
