name: Scala CI

on:
  push:
    branches:
      - main  # or master, or whatever your main branch is named
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Scala and sbt
      uses: olafurpg/setup-scala@v10
      with:
        java-version: adopt@1.11  # or your desired version

    - name: Cache sbt dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.ivy2/cache
          ~/.cache/coursier
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', '**/project/**') }}

    - name: Run tests
      run: sbt test
